apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 3  # 원하는 파드 수
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: spring-app-image:latest  # Minikube에서 사용할 이미지
          imagePullPolicy: IfNotPresent  # 추가된 부분
          ports:
            - containerPort: 8899  # 애플리케이션이 사용하는 포트
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80  # 서비스의 노출 포트
      targetPort: 8899  # 컨테이너 포트
  type: NodePort  # LoadBalancer | NodePort로 변경
